version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b android-4.14-stable xnxx
           cd xnxx
           bash build.sh 
  
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
